-- MySQL Script generated by MySQL Workbench
-- Fri Oct  8 15:52:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema daejeondb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema daejeondb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `daejeondb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `daejeondb` ;

-- -----------------------------------------------------
-- Table `daejeondb`.`application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daejeondb`.`application` ;

CREATE TABLE IF NOT EXISTS `daejeondb`.`application` (
  `name` VARCHAR(20) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(20) NULL DEFAULT NULL,
  `degree` VARCHAR(20) NULL DEFAULT '선택안함',
  `courses` VARCHAR(50) NULL DEFAULT '입력하지 않음',
  `choose` VARCHAR(20) NULL DEFAULT NULL,
  `agreement` VARCHAR(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
